// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo055s7nvDh8sUI8kS2BbDwg_jRO-pQ-E',
    appId: '1:215524051908:web:2b705a8e5342327d157291',
    messagingSenderId: '215524051908',
    projectId: 'store-app-c267f',
    authDomain: 'store-app-c267f.firebaseapp.com',
    storageBucket: 'store-app-c267f.appspot.com',
    measurementId: 'G-64C1Q26LEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3BQTiL-_anNQdtvVvAurIhT4LKwSMM8',
    appId: '1:215524051908:android:0640460989e2661b157291',
    messagingSenderId: '215524051908',
    projectId: 'store-app-c267f',
    storageBucket: 'store-app-c267f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ae-yh8HlsMhDWEtViVbQz9UORHL51qQ',
    appId: '1:215524051908:ios:0a0d88f3ff90ae53157291',
    messagingSenderId: '215524051908',
    projectId: 'store-app-c267f',
    storageBucket: 'store-app-c267f.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ae-yh8HlsMhDWEtViVbQz9UORHL51qQ',
    appId: '1:215524051908:ios:0a0d88f3ff90ae53157291',
    messagingSenderId: '215524051908',
    projectId: 'store-app-c267f',
    storageBucket: 'store-app-c267f.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo055s7nvDh8sUI8kS2BbDwg_jRO-pQ-E',
    appId: '1:215524051908:web:661ab02cf6ec583d157291',
    messagingSenderId: '215524051908',
    projectId: 'store-app-c267f',
    authDomain: 'store-app-c267f.firebaseapp.com',
    storageBucket: 'store-app-c267f.appspot.com',
    measurementId: 'G-1K16PBFCCZ',
  );
}
